language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run pipeline sh -c "snakemake -j 8 --use-conda --conda-prefix /home/PIA3 --config in_dir=/home/PIA3/test_data out_dir=/home/out db=/home/PIA3/classification_opsins_full_aa.fasta cds=True --verbose"